
name: IMLP
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - six==1.17.0
      - kaleido>=0.2.1
      - numpy==2.0.2
      - pandas==2.3.0
      - matplotlib~=3.7.1
      - seaborn~=0.12.2
      - scikit-learn==1.6.1
      - machine-learning-datasets~=0.1.23
      - scipy==1.13.1
      - tqdm==4.67.1
      - ipython>=7.23.0
      - dowhy~=0.10.1
      - torchinfo~=1.8.0
      - SALib~=1.4.7
      - PyALE~=1.1.3
      - transformers~=4.32.0
      - protobuf~=3.20.3
      - witwidget~=1.8.1
      - bayesian-optimization~=1.4.3
      - scikeras[tensorflow]~=0.11.0
      - econml~=0.14.1
      - bertviz~=1.4.0
      - rulefit~=0.3.1
      - pytorch-lightning~=2.1.0
      - efficientnet-pytorch~=0.7.1
      - fairlearn~=0.7
      - flask-compress~=1.14
      - nltk~=3.8.1
      - pydot~=1.4.2
      - networkx~=3.2
      - PDPbox~=0.3.0
      - gaminet~=0.6.1
      - lxml~=4.9.3
      - lit-nlp~=0.5.0
      - rouge-score~=0.1.2
      - sklearn-genetic-opt~=0.10.1
      - BlackBoxAuditing~=0.1.54
      - distython==0.0.3
      - tensorflow-lattice~=2.0.13
      - interpret~=0.4.4
      - captum~=0.6.0
      - mlxtend~=0.22.0
      - lime~=0.2.0.1
      - torch~=2.1.0
      - torchvision~=0.16.0
      - opencv-python~=4.5.1
      - statsmodels~=0.14.0
      - xgboost~=2.0.0
      - lightgbm~=4.0.0
      - aif360~=0.5.0
      - catboost~=1.2
      - ray~=2.7.1
      - alibi~=0.9.4
      - tensorflow~=2.14.0
      - shap==0.41.0
      - adversarial-robustness-toolbox~=1.12.2
